language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: NNhA6cuzqODMDbA6vCAPaVT9lfYCKBPe/HyMVT7V0yaQwaIpR1KYhf2Xkhk/nJzAs32Llfd0vBrulx3Ycx9lyn5iJ1hekqW3GpstLu0lIV59HcWiA7XXxKL2foJ6KNIrbwe8zS+BFNIOEDeOWXr2KULh+ZhTqOlOlwOFHhQubrpnNg5AJyVBSaIdADCa/Jz9IjNTrYd25hOWnqFBBSIdWUw0CyR/F01TMJSMWrrI5qjpWI2IOGHKMQ4P9BfLJLfK/pjQJzc6gLuVUi0lN6pctdg7k6QQwzT+/xzhYMs0brr7KGTm00XtjYSbsM1EHcB3I87RN4zmiwoLPk/Ku/nAPwWHuOUXndoQd6WYUjzILDDeKSiMdh1c8j/IMFOckTxtzxiwCF/Y01gqaz+Qz1/+pFgdz7P5dO03sCm9Ff/lOmIA51pObaIvy5B6HjXmdBhtvH4hxw9NtV6Wv4QYWzV+045gOOwyBafownrtYPTreObIqCJwsp0mZU8ctYR6T9e+GsZpCY3R83l6yKfP+KEU45e9t+7yW2zQoH6hFm9q12EQ9xhZViCaEsmK9Gckym0dFdz/Yymt/IZxEQrLGA99trbuYnvRfP+svS6uY3XE8p9J3knwVpMH5QzJHuH9uamA/0ZT8xccgfwpRwiIG/TJgwj7mSusyYe6jL6pwMWYm0s=
